### ISSUE TITLE
Full RFC 5424 Support

### ISSUE THREAD

**Issue by ericsnowcurrently** [papertrail/remote_syslog2#153]
Currently the Packet type (in syslog/packet.go) is missing the following:

* Proc ID
* Msg ID
* Structured Data

Do you have any objections to Packet supporting those?  If not, I'd be willing to provide a PR.

It would also be nice if the field names matched the field names in the RFC.  Would you object to changing those ("Tag" -> "AppName", "Time" -> "Timestamp")?

**Comment by johlym** [comment]
Hi @ericsnowcurrently 

To your first question: my only objection is that Papertrail won't do anything with these data points so including them in remote_syslog2, in my mind, wouldn't have any benefit because:

* Papertrail doesn't do anything with these fields, so they would be dropped, anyway.
* These three data points can be included in the message and as such, be searchable and formatted how you desire.

Thing brings me to a question I have:

* `PROC ID` - `having no interoperable meaning, except that a change in the value indicates there has been a discontinuity in syslog reporting.` ([source](https://tools.ietf.org/html/rfc5424#section-6.2.6)) Do you actively use this field when sending to Papertrail? I'd be curious to hear more about this.

Regarding the field names matching [RFC 5424](https://tools.ietf.org/html/rfc5424): I don't see a problem with keeping up with the most current standard; `TAG` came from [RFC 3164](https://www.ietf.org/rfc/rfc3164.txt) and is still widely used to describe the process or app (even in the [Wikipedia article](https://en.wikipedia.org/wiki/Syslog#Message)). That's not to say you're wrong, though. 5424 did make 3164 obsolete, for sure. 

@troy @leon what do you think?

**Comment by troy** [comment]
I don't have a strong opinion about the possible new fields, as long as they don't affect existing consumers.

Regarding the field names, "tag" is used more commonly than "appname" for the reason @johlym gave, and "time" is clear enough, so I don't see a benefit from changing them.

**Comment by ericsnowcurrently** [comment]
I'm looking at using the remote_syslog2/syslog package in my own project, independent of Papertrail.  For my use case those fields are required.  If they are not set on Packet then the resulting serialization should be exactly the same.

**Comment by johlym** [comment]
hey @ericsnowcurrently, are you looking to just use the `remote_syslog2/syslog` library or the whole app? What's the end goal? I might be misinterpreting your request; extra detail would be much appreciated :)

**Comment by ericsnowcurrently** [comment]
Don't sweat it.  I ended up rolling my own. :)
